name: expense_control_app
description: App de control de gastos con arquitectura limpia e Isar local.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.2
  shared_preferences: ^2.3.2
  isar: ^3.1.0+1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.3.11
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/env/dev.json
